# Generated by Django 5.2.14 on 2026-05-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecontentembedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursecontentembedding',
            new_name='courses_cou_course__2c54b3_idx',
            old_name='courses_cou_course__9fffae_idx',
        ),
    ]
